apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dev-box-aks
  name: dev-box-aks
spec:
  nodeSelector:
    dev-box: "true"
  containers:
  - image: prom11/dev-box-aks
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
    name: dev-box
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 3000; done;" ]
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
  hostNetwork: true
  restartPolicy: Always
